In [1]:
import keras
from keras.datasets import mnist
# from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils# for custom objects



Using TensorFlow backend.


In [0]:


batch_size = 32
num_classes = 10
epochs = 200

In [5]:
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
print(x_train.shape[0])
print(x_train.shape[1])

x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
print(x_test.shape[0])
print(x_test.shape[1])
x_test.shape[0]
input_shape = (28, 28, 1)
# Making sure that the values are float so that we can get decimal points after division
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
# Normalizing the RGB codes by dividing it to the max RGB value.
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print('Number of images in x_train', x_train.shape[0])
print('Number of images in x_test', x_test.shape[0])

60000
28
10000
28
x_train shape: (60000, 28, 28, 1)
Number of images in x_train 60000
Number of images in x_test 10000


In [4]:

# The data, shuffled and split between train and test sets:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

11493376/11490434 [==============================] - 0s 0us/step
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples


In [0]:
# Convert class vectors to binary class matrices.
#y_train = keras.utils.to_categorical(y_train, num_classes)

#y_test = keras.utils.to_categorical(y_test, num_classes)




In [0]:
#y_train

In [0]:
#y_test

In [6]:
import numpy as np
print(np.unique(y_train,return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8), array([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949]))


In [0]:
#x_train = x_train.astype('float32')
#x_test = x_test.astype('float32')
#x_train /= 255
#x_test /= 255


In [7]:
x_train

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [8]:
# Initialize the model
model = Sequential()

In [9]:
x_test

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [10]:
model.add(Conv2D(28, kernel_size=(3,3), input_shape=(28,28,1))) # no .of filters =28,# size of filters =(3,3) 

In [11]:
model.add(MaxPooling2D(pool_size=(2, 2)))

In [0]:
model.add(Flatten()) # Flattening the 2D arrays for fully connected layers

In [0]:
import tensorflow as tf

In [0]:
model.add(Dense(128, activation=tf.nn.relu))

In [15]:
model.add(Dropout(0.2))


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [0]:
model.add(Dense(10,activation=tf.nn.softmax))

In [17]:
# Compiling the model
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])

In [18]:
# fit the model
model.fit(x=x_train,y=y_train,epochs=10)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/10





60000/60000 [==============================] - 40s 659us/step - loss: 0.2076 - acc: 0.9369
Epoch 2/10
60000/60000 [==============================] - 39s 644us/step - loss: 0.0822 - acc: 0.9744
Epoch 3/10
60000/60000 [==============================] - 39s 644us/step - loss: 0.0575 - acc: 0.9818
Epoch 4/10
60000/60000 [==============================] - 39s 645us/step - loss: 0.0443 - acc: 0.9858
Epoch 5/10
60000/60000 [==============================] - 38s 640us/step - loss: 0.0342 - acc: 0.9889
Epoch 6/10
60000/60000 [==============================] - 38s 642us/step - loss: 0.0292 - acc: 0.9899
Epoch 7/10
60000/60000 [==============================] - 39s 644us/step - loss: 0.0238 - acc: 0.9917
Epoch 8/10
60000/60000 [==============================] - 39s 644us/step - loss: 0.0212 - acc: 0.9929
Epoch 9/10
60000/60000 [==============================] - 39s 653us/step - loss: 0

In [19]:
model.evaluate(x_test,y_test)

10000/10000 [==============================] - 2s 202us/step


[0.06032931500424857, 0.9857]